export const useGoetia = () => {
  const hierarquiasGoeticas = [
    { titulo: "A Trindade Infernal", daemons: [{ nome: "Lúcifer", rank: "Imperador", slug: "lucifer" }, { nome: "Belzebu", rank: "Príncipe", slug: "belzebu" }, { nome: "Astaroth", rank: "Grã-Duquesa", slug: "astaroth" }, { nome: "Lilith", rank: "Matriarca", slug: "lilith" }] },
    { titulo: "Os Reis", daemons: [{ numero: 1, nome: "Bael", rank: "Rei", slug: "bael" }, { numero: 9, nome: "Paimon", rank: "Rei", slug: "paimon" }, { numero: 13, nome: "Beleth", rank: "Rei", slug: "beleth" }, { numero: 20, nome: "Purson", rank: "Rei", slug: "purson" }, { numero: 32, nome: "Asmodeus", rank: "Rei", slug: "asmodeus-goetia" }, { numero: 45, nome: "Vine", rank: "Rei", slug: "vine" }, { numero: 51, nome: "Balam", rank: "Rei", slug: "balam" }, { numero: 61, nome: "Zagan", rank: "Rei", slug: "zagan" }, { numero: 68, nome: "Belial", rank: "Rei", slug: "belial" }] },
    { titulo: "Os Duques", daemons: [{ numero: 2, nome: "Agares", rank: "Duque", slug: "agares" }, { numero: 6, nome: "Valefor", rank: "Duque", slug: "valefor" }, { numero: 8, nome: "Barbatos", rank: "Duque", slug: "barbatos" }, { numero: 11, nome: "Gusion", rank: "Duque", slug: "gusion" }, { numero: 15, nome: "Eligos", rank: "Duque", slug: "eligos" }, { numero: 16, nome: "Zepar", rank: "Duque", slug: "zepar" }, { numero: 18, nome: "Bathin", rank: "Duque", slug: "bathin" }, { numero: 19, nome: "Sallos", rank: "Duque", slug: "sallos" }, { numero: 23, nome: "Aim", rank: "Duque", slug: "aim" }, { numero: 26, nome: "Buné", rank: "Duque", slug: "bune" }, { numero: 28, nome: "Berith", rank: "Duque", slug: "berith" }, { numero: 29, nome: "Astaroth", rank: "Duque", slug: "astaroth-goetia" }, { numero: 41, nome: "Focalor", rank: "Duque", slug: "focalor" }, { numero: 42, nome: "Vepar", rank: "Duque", slug: "vepar" }, { numero: 47, nome: "Vual", rank: "Duque", slug: "vual" }, { numero: 49, nome: "Crocell", rank: "Duque", slug: "crocell" }, { numero: 52, nome: "Alloces", rank: "Duque", slug: "alloces" }, { numero: 54, nome: "Murmur", rank: "Duque", slug: "murmur" }, { numero: 56, nome: "Gremory", rank: "Duque", slug: "gremory" }, { numero: 60, nome: "Vapula", rank: "Duque", slug: "vapula" }, { numero: 64, nome: "Haures", rank: "Duque", slug: "haures" }, { numero: 67, nome: "Amdusias", rank: "Duque", slug: "amdusias" }, { numero: 71, nome: "Dantalion", rank: "Duque", slug: "dantalion" }] },
    { titulo: "Os Príncipes", daemons: [{ numero: 3, nome: "Vassago", rank: "Príncipe", slug: "vassago" }, { numero: 12, nome: "Sitri", rank: "Príncipe", slug: "sitri" }, { numero: 22, nome: "Ipos", rank: "Príncipe", slug: "ipos" }, { numero: 33, nome: "Gaap", rank: "Príncipe", slug: "gaap" }, { numero: 36, nome: "Stolas", rank: "Príncipe", slug: "stolas" }, { numero: 55, nome: "Orobas", rank: "Príncipe", slug: "orobas" }, { numero: 70, nome: "Seere", rank: "Príncipe", slug: "seere" }] },
    { titulo: "Os Marqueses", daemons: [{ numero: 4, nome: "Samigina", rank: "Marquês", slug: "samigina" }, { numero: 7, nome: "Amon", rank: "Marquês", slug: "amon" }, { numero: 14, nome: "Leraje", rank: "Marquês", slug: "leraje" }, { numero: 24, nome: "Naberius", rank: "Marquês", slug: "naberius" }, { numero: 27, nome: "Ronove", rank: "Marquês", slug: "ronove" }, { numero: 30, nome: "Forneus", rank: "Marquês", slug: "forneus" }, { numero: 35, nome: "Marchosias", rank: "Marquês", slug: "marchosias" }, { numero: 37, nome: "Phenex", rank: "Marquês", slug: "phenex" }, { numero: 43, nome: "Sabnock", rank: "Marquês", slug: "sabnock" }, { numero: 44, nome: "Shax", rank: "Marquês", slug: "shax" }, { numero: 59, nome: "Orias", rank: "Marquês", slug: "orias" }, { numero: 63, nome: "Andras", rank: "Marquês", slug: "andras" }, { numero: 65, nome: "Andrealphus", rank: "Marquês", slug: "andrealphus" }, { numero: 66, nome: "Cimejes", rank: "Marquês", slug: "cimejes" }, { numero: 69, nome: "Decarabia", rank: "Marquês", slug: "decarabia" }] },
    { titulo: "Os Presidentes", daemons: [{ numero: 5, nome: "Marbas", rank: "Presidente", slug: "marbas" }, { numero: 10, nome: "Buer", rank: "Presidente", slug: "buer" }, { numero: 17, nome: "Botis", rank: "Presidente", slug: "botis" }, { numero: 21, nome: "Marax", rank: "Presidente", slug: "marax" }, { numero: 25, nome: "Glasya-Labolas", rank: "Presidente", slug: "glasya-labolas" }, { numero: 31, nome: "Foras", rank: "Presidente", slug: "foras" }, { numero: 39, nome: "Malphas", rank: "Presidente", slug: "malphas" }, { numero: 48, nome: "Haagenti", rank: "Presidente", slug: "haagenti" }, { numero: 53, nome: "Camio", rank: "Presidente", slug: "camio" }, { numero: 57, nome: "Ose", rank: "Presidente", slug: "ose" }, { numero: 58, nome: "Amy", rank: "Presidente", slug: "amy" }, { numero: 62, nome: "Valac", rank: "Presidente", slug: "valac" }] },
    { titulo: "Os Condes", daemons: [{ numero: 34, nome: "Furfur", rank: "Conde", slug: "furfur" }, { numero: 38, nome: "Halphas", rank: "Conde", slug: "halphas" }, { numero: 40, nome: "Raum", rank: "Conde", slug: "raum" }, { numero: 46, nome: "Bifrons", rank: "Conde", slug: "bifrons" }, { numero: 72, nome: "Andromalius", rank: "Conde", slug: "andromalius" }] },
    { titulo: "Os Cavaleiros", daemons: [{ numero: 50, nome: "Furcas", rank: "Cavaleiro", slug: "furcas" }] },
    { titulo: "Entidades Cósmicas", daemons: [{ nome: "Ouroboros", rank: "Entidade Cósmica", slug: "ouroboros" }] }
  ];

  // Importação automática com segurança
  const arquivos = import.meta.glob('~/data/daemons/*.js', { eager: true });
  const detalhesDaemons = {};

  for (const path in arquivos) {
    const conteudo = arquivos[path].default;
    // Só adiciona se o arquivo for válido e tiver um slug
    if (conteudo && conteudo.slug) {
      detalhesDaemons[conteudo.slug] = conteudo;
    }
  }

  return { hierarquiasGoeticas, detalhesDaemons }
}